Specify dns server redirection per domain
NethServer/nethserver-dnsmasq pull request #18
Opened 2020-03-05 16:43 UTC by stephdl

2020-03-05 17:05 UTC, gsanchietti requested changes
Please also add the new prop to the README.

2020-03-05 17:05 UTC, gsanchietti commented on root/etc/e-smith/templates/etc/dnsmasq.conf/55DomainRedirection
> +# warded as usual.
Move this to the PR description.
Also bear in mind that is not intended only for private nameserver, but mostly.

2020-03-09 09:13 UTC, gsanchietti approved these changes

2020-03-09 09:15 UTC, gsanchietti commented
Since is not clear how many users use such function, I'm willing to leave this new feature without UI.
Also, before creating a new UI, we probably need a refactor of the DNS page.
IMO such refactor is out of the scope for now.

What to you think @filippocarletti @nrauso ?

2020-03-09 14:45 UTC, filippocarletti approved these changes

2020-03-09 14:50 UTC, gsanchietti commented
Please create the related issue and improve the README: new doc is out of context and has incorrect formatting.

2020-03-09 16:06 UTC, stephdl commented
Yes the UI is not so easy to design it, surely we need to break the actual page

2020-03-09 16:59 UTC, merged